--- 
- 
  ansible.builtin.apt: 
    name: 
      - unzip
      - wget
  name: "install unzip and wget"
- 
  ansible.builtin.get_url: 
    dest: /opt/
    mode: 493
    url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.3.zip"
  name: "download the zip file"
- 
  ansible.builtin.file: 
    mode: "0755"
    path: /opt/sonarqube/
    state: directory
  name: "Create /opt/sonarqube/"
- 
  ansible.builtin.unarchive: 
    dest: /opt/
    remote_src: true
    src: /opt/sonarqube-7.9.3.zip
  name: "Extract the zip file"
- 
  ansible.builtin.copy: 
    dest: /opt/sonarqube/
    follow: true
    remote_src: true
    src: /opt/sonarqube-7.9.3/
  name: "Copy /opt/sonarqube/"
- 
  ansible.builtin.file: 
    path: /opt/sonarqube-7.9.3.zip
    state: absent
  name: "remove the zip file"
- 
  ansible.builtin.shell: "useradd -c \"user to run SonarQube\" -d /opt/sonarqube -g sonar sonar"
  name: "add user to run sonar"
- 
  ansible.builtin.shell: "chown sonar:sonar /opt/sonarqube -R"
  name: "change ownership"
- 
  ansible.builtin.template: 
    dest: /opt/sonarqube/conf/sonar.properties
    force: true
    src: templates/sonar.properties.j2
  name: "Configuring the SonarQube Server"
- 
  ansible.builtin.lineinfile: 
    line: RUN_AS_USER=sonar
    path: /opt/sonarqube/bin/linux-x86-64/sonar.sh
    regexp: "^#RUN_AS_USER="
    state: present
  name: "Update user in sonar.sh filee"
- 
  ansible.builtin.template: 
    dest: /etc/systemd/system/sonar.service
    force: true
    src: templates/sonarqube.service.j2
  name: "create a service file"
