[nfs]
172.31.83.238 ansible_user='ec2-user'

[webservers]
172.31.0.38 ansible_user='ec2-user'
172.31.10.253 ansible_user='ec2-user'cd

[db]
172.31.86.142 ansible_user='ubuntu' 

[lb]
172.31.95.176 ansible_user='ubuntu'